import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs) {
	return twMerge(clsx(inputs));
}

export function toWebP(src) {
	return src.replace(/\.(jpe?g|png)$/i, '.webp');
}

// Widths generated by tools/generate-responsive-images.js.
export const RESPONSIVE_WIDTHS = [400, 800, 1280, 1920];

// Build a srcset string of responsive variants ({base}-{w}.{ext}). encodeURI
// keeps "/" but escapes spaces so filenames like "riding3 view.jpeg" (which
// would otherwise break srcset parsing) work.
export function srcSet(src, ext) {
	const base = src.replace(/\.(jpe?g|png)$/i, '');
	return RESPONSIVE_WIDTHS
		.map((w) => `${encodeURI(`${base}-${w}.${ext}`)} ${w}w`)
		.join(', ');
}